language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
branches:
  only:
    - master
install:
  - pip install . -r dev-requirements.txt
script:
  - py.test --cov wurlitzer test.py
after_success:
  - codecov
matrix:
  include:
    - os: osx
      python: 3.6
    - os: osx
      python: 2.7
    - os: linux
      dist: xenial
      python: 3.7
